-- ORACLE 

SELECT F.FLAVOR 
  FROM FIRST_HALF F
       INNER JOIN ICECREAM_INFO I
       ON F.FLAVOR = I.FLAVOR
 WHERE F.TOTAL_ORDER > 3000
   AND I.INGREDIENT_TYPE = 'fruit_based';

-- ORACLE 은 AS 사용 불가